[package]
name = "network-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wifi-rs = "0.2.4"
local-ip-address = "0.6.1"
sysinfo = "0.30.12"